### ISSUE TITLE
Robot arm not editable

### ISSUE THREAD

**Issue by jumpjack** [Rhoban/onshape-to-robot-examples#1]
How can I copy the robot arm into my onshape for editing? It's "view only".

**Comment by Gregwar** [comment]
Hello
Should be ok now, can you confirm ?

**Comment by Gregwar** [comment]
(I checked the other examples as well, everything should be public copiable now)

**Comment by jumpjack** [comment]
Probably it was my mistake: it's still "view only", but I didn't notice I logged out from onshape account; now I logged, I still see "view only", but I also see the button "make a copy to edit:

![image](https://github.com/Rhoban/onshape-to-robot-examples/assets/1620953/1daeba6b-45f5-4c38-8027-381471696f0b)

**Comment by Gregwar** [comment]
I see, glad you solved your problem!
